name: Fetch and save JSON

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 12 *'  # Run every 1 December

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch JSON from API
        run: |
          mkdir -p json
          for year in {1910..2100}; do
            mkdir -p "json/$year"
            curl -sS "https://kalenderindonesia.com/api/9010b0cbc2affdbf/kalender/masehi/$year" -o "json/$year/data.json"
            for month in {0..11}; do
              mkdir -p "json/$year/$month"
              echo $(jq .data[$month] "json/$year/data.json") > "json/$year/$month/data.json"
            done
          done

      - name: Commit JSON data
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git config --global credential.helper store
          git pull origin main
          git add .
          git commit -m "Update JSON data [skip ci]"
          git push origin main
